# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonse_emne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emne', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonser',
            name='kvalik',
        ),
        migrations.AddField(
            model_name='annonse_emne',
            name='annonse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdshome.Annonser'),
        ),
        migrations.AddField(
            model_name='annonse_emne',
            name='emne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdshome.Emne'),
        ),
    ]
