# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0002_auto_20160421_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonser',
            name='tags',
            field=models.CharField(choices=[('JV', 'Java'), ('PH', 'PHP'), ('WP', 'Wordpress'), ('AN', 'Android'), ('IO', 'iOS'), ('PY', 'Python'), ('NT', '.NET'), ('IN', 'Ingen')], default='IN', max_length=100),
        ),
    ]
