# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0003_auto_20160422_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonser',
            name='tags',
            field=models.CharField(choices=[('Java', 'Java'), ('PHP', 'PHP'), ('Wordpress', 'Wordpress'), ('Android', 'Android'), ('iOS', 'iOS'), ('Python', 'Python'), ('.NET', '.NET'), ('Ingen', 'Ingen')], default='Ingen', max_length=100),
        ),
    ]
