# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0004_auto_20160422_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonser',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
