# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0006_brukerinformasjon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brukerinformasjon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
