# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wdshome', '0007_auto_20160425_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utviklere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=150)),
                ('dato', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
