# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdshome', '0008_utviklere'),
    ]

    operations = [
        migrations.AddField(
            model_name='utviklere',
            name='epost',
            field=models.EmailField(default='example@mail.com', max_length=254),
        ),
    ]
