# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wdshome', '0009_utviklere_epost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Søknader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(auto_now=True)),
                ('tekst', models.TextField(max_length=1000)),
                ('epost', models.EmailField(default='example@mail.com', max_length=254)),
                ('annonse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wdshome.Annonser')),
                ('søker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
